{% set name = "elastic-vasp" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/elastic_vasp-{{ version }}.tar.gz
  sha256: 948b39debe4b18a0829681f4237fad650cf5b2c76c531a54657a7e6ecabc8951

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base

test:
  imports:
    - elastic_vasp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/prnvrvs/elastic_vasp
  summary: This package is based on python to create deformed structure and calculate second-order elastic constants from strain-energy relationship. This tool is only compatible with DFT package VASP.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
